#! /usr/bin/env python3
# Sanity for Robot
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()


K = int(input())
s = input()

MIN_K = 1;
MAX_K = 1e5;

ensure(K, MIN_K, MAX_K)

if len(s) != K:
    fail()

for c in s:
    if c not in "NESW":
        fail()

print(1)