#! /usr/bin/env python3
# Sanity for Vases
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

MIN_N = 0;
MAX_N = 1e5;

N = int(input())
ensure(N, MIN_N, MAX_N)

print(1)