#! /usr/bin/env python3
# Sanity for Addition
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

MIN_N = 0;
MAX_N = 1e9;

a, b = list(map(int, input().split()))
ensure(a, MIN_N, MAX_N)
ensure(b, MIN_N, MAX_N)

print(1)