#! /usr/bin/env python3
# Sanity for Robot
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

MIN_N = 2;
MAX_N = 1e5;
MIN_X = 1;
MAX_X = 1e4;
MIN_Y = 1;
MAX_Y = 1e4;

N = int(input())
ensure(N, MIN_N, MAX_N)
for i in range(N):
    x, y = list(map(int, input().split()))
    ensure(x, MIN_X, MAX_X)
    ensure(y, MIN_Y, MAX_Y)

print(1)